fun main() {
    val firstDebitCard = FirstDebitCard()
    println(firstDebitCard.getCardBalanceInfo())
    println("After topping up the card by 5 000:")
    firstDebitCard.addMoney(5000.0)
    println(firstDebitCard.getAllFundsInfo())
    println("After payment by 3 000:")
    firstDebitCard.toPay(3000.0)
    println(firstDebitCard.getAllFundsInfo())
    println("After payment by 2 000:")
    firstDebitCard.toPay(2000.0)
    println(firstDebitCard.getAllFundsInfo())
    println("After payment by 3 000:")
    firstDebitCard.toPay(3000.0)
    println(firstDebitCard.getAllFundsInfo())
    println(firstDebitCard.getBenefitInfo())

    println("--------------------")
    val secondDebitCard = SecondDebitCard()
    println(secondDebitCard.getCardBalanceInfo())
    println("After topping up the card by 5 000:")
    secondDebitCard.addMoney(5000.0)
    println("and payment by 3 000:")
    secondDebitCard.toPay(3000.0)
    println(secondDebitCard.getAllFundsInfo())
    println(secondDebitCard.getBenefitInfo())

    println("--------------------")
    val firstCreditCard = FirstCreditCard()
    println(firstCreditCard.getCardBalanceInfo())
    println("After topping up the card by 5 000:")
    firstCreditCard.addMoney(5000.0)
    println(firstCreditCard.getAllFundsInfo())
    println()
    println(firstCreditCard.getCardBalanceInfo())
    println("After payment by 5 000:")
    firstCreditCard.toPay(5000.0)
    println(firstCreditCard.getAllFundsInfo())
    println()
    println(firstCreditCard.getCardBalanceInfo())
    println("After payment by 3 000:")
    firstCreditCard.toPay(3000.0)
    println(firstCreditCard.getAllFundsInfo())
    println()
    println(firstCreditCard.getCardBalanceInfo())
    println("After topping up the card by 2 000:")
    firstCreditCard.addMoney(2000.0)
    println(firstCreditCard.getAllFundsInfo())
    println()
    println(firstCreditCard.getCardBalanceInfo())
    println("After topping up the card by 2 000:")
    firstCreditCard.addMoney(2000.0)
    println(firstCreditCard.getAllFundsInfo())
    println(firstCreditCard.getBenefitInfo())
    println()
    println(firstCreditCard.getCardBalanceInfo())
    println("After payment by 50 000:")
    firstCreditCard.toPay(50_000.0)
    println(firstCreditCard.getAllFundsInfo())
}